name: Tests

on:
  push:
    branches:
      - main
      - release*

  pull_request:
    paths:
      - src/**
      - config/**
      - tests/**
      - .github/workflows/tests.yml

  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ vars.RUNNER_OS || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.3
          - 8.4

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: composer test -- --testdox
